spring:
  application:
    version: @project.version@
    name: @project.artifactId@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: factoring-hikari-pool
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
springdoc:
  swagger-ui:
    url: /openapi/api-spec.yml
    path: docs
    disable-swagger-default-url: true
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
server:
  port: 8080